AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "form-submission cloudformation template"
Parameters:
  APIBasePath:
    Description: API Base Path e.g; /api/*
    Type: String
  AppEnv:
    Description: App Deployment Environment
    Type: String
    AllowedValues: ['Local', 'Dev', 'QA', 'Stage', 'Prod']

Globals:
  Function:
    Timeout: 10

Resources:
  Proxy:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Comment: "Form data"
        DefaultRootObject: "index.html"
        Enabled: true
        HttpVersion: http2
        Origins:
          - Id: s3-frontend
            DomainName: !GetAtt FrontendBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: 
                Fn::Sub: 'origin-access-identity/cloudfront/${ProxyFrontendBucketAccess}'
          - Id: api-gateway
            DomainName: !Sub "${FormDataApi}.execute-api.${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginKeepaliveTimeout: '20'
              OriginReadTimeout: '20'
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: ['TLSv1', 'TLSv1.1', 'TLSv1.2'] 
        DefaultCacheBehavior:
          Compress: 'true'
          AllowedMethods: ['GET', 'HEAD', 'OPTIONS']
          ForwardedValues:
            QueryString: false
          TargetOriginId: s3-frontend
          ViewerProtocolPolicy : redirect-to-https
        CacheBehaviors:
        - AllowedMethods: ['HEAD', 'OPTIONS', 'GET', 'POST', 'PUT', 'PATCH', 'DELETE']
          TargetOriginId: api-gateway
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: none
            Headers: ['Accept', 'Accept-Charset', 'Accept-Datetime', 'Accept-Language', 'Accept-Encoding', 'Referer', 'Origin', 'Authorization']
          ViewerProtocolPolicy: https-only
          MinTTL: '0'
          MaxTTL: '0'
          DefaultTTL: '0'
          PathPattern: !Sub "/${APIBasePath}/*"
        #CustomErrorResponses:
        #- ErrorCode: '403'
        #  ResponsePagePath: "/index.html"
        #  ResponseCode: '200'
        #  ErrorCachingMinTTL: '30'

  ProxyFrontendBucketAccess:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Form data frontend access'

  FrontendBucket:
    Type: AWS::S3::Bucket

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          -
            Effect: Allow
            Action: 's3:GetObject'
            Resource:
              - !Sub "arn:aws:s3:::${FrontendBucket}/*"
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${ProxyFrontendBucketAccess}"

  FormDataApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref APIBasePath
      EndpointConfiguration: REGIONAL
      
  FormDataLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: service/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Select [1, !Split ['/', !GetAtt FormDataTable.Arn]]
      Events:
        FormDataApi:
          Type: Api
          Properties:
            Path: /submit
            Method: post
            RestApiId: !Ref FormDataApi

  FormDataTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:       
        - 
          AttributeName: "Id"
          AttributeType: "S"
        - 
          AttributeName: "CreatedAt"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "Id"
          KeyType: "HASH"
        - 
          AttributeName: "CreatedAt"
          KeyType: "RANGE"
      TableName: !Sub "${AppEnv}_Form_Data"
      BillingMode: PAY_PER_REQUEST          

Outputs:
  CloudFrontURL:
    Description: "App URL"
    Value: !Sub "https://${Proxy.DomainName}"
  CloudFrontPostURL:
    Description: "App form action URL"
    Value: !Sub "https://${Proxy.DomainName}/${APIBasePath}/submit"
  FormFrontendS3Bucket:
    Description: "Frontend S3 bucket"
    Value: !GetAtt FrontendBucket.DomainName
  FormDataLambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt FormDataLambda.Arn
  FormDataDynamoDBTableName:
    Description: "Dynamodb table used to store form data"
    Value: !Select [1, !Split ['/', !GetAtt FormDataTable.Arn]]

